<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\ActivityLogController;
use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\AuditLogController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\ExpenseCategoryController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\LeaveRequestController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ProductCategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use Illuminate\Support\Facades\Route;
use Laravel\Fortify\Features;

Route::inertia('/', 'welcome', [
    'canRegister' => Features::enabled(Features::registration()),
])->name('home');

Route::middleware(['auth', 'verified'])->group(function () {
    Route::inertia('dashboard', 'dashboard')->name('dashboard');
    Route::apiResource('products', ProductController::class);
    Route::apiResource('categories', ProductCategoryController::class);
    Route::get('categories/{category}/products', [ProductCategoryController::class, 'products']);
    Route::get('products/{product}/categories', [ProductController::class, 'categories']);
    Route::put('products/{product}/categories', [ProductController::class, 'syncCategories']);
    Route::put('categories/{category}/products', [ProductCategoryController::class, 'syncProducts']);
    Route::post('reports',[ProductController::class, 'report']);
    Route::get('reports', [ProductController::class, 'showReport'])->name('reports');
    Route::get('settings', [ProductController::class, 'settings'])->name('settings');
    Route::get('import', [ProductController::class, 'import'])->name('import');
    Route::post('import', [ProductController::class, 'doImport']);
    Route::get('search', [ProductController::class, 'search'])->name('search');
    Route::get('autocomplete', [ProductController::class, 'autocomplete']);
    Route::get('inventory', [ProductController::class, 'inventory'])->name('inventory');
    Route::get('sales', [ProductController::class, 'sales'])->name('sales');
    Route::get('sales-report', [ProductController::class, 'salesReport'])->name('sales-report');
    Route::get('sales-report-data', [ProductController::class, 'salesReportData']);
    Route::get('stock-alerts', [ProductController::class, 'stockAlerts'])->name('stock-alerts');
    Route::get('stock-summary', [ProductController::class, 'stockSummary'])->name('stock-summary');
    Route::get('stock-summary-data', [ProductController::class, 'stockSummaryData']);
    Route::get('stock-summary-export', [ProductController::class, 'stockSummaryExport']);
    Route::get('sales-export', [ProductController::class, 'salesExport']);
    Route::get('low-stock-products', [ProductController::class, 'lowStockProducts']);
    Route::get('out-of-stock-products', [ProductController::class, 'outOfStockProducts']);
    Route::get('expired-products', [ProductController::class, 'expiredProducts'])->name('expired-products');
    Route::get('expired-products-data', [ProductController::class, 'expiredProductsData']);
    Route::get('activitylog',[ActivityLogController::class, 'index']);
    Route::get('backup', [ProductController::class, 'backup'])->name('backup');
    Route::post('backup', [ProductController::class, 'doBackup']);
    Route::get('backup/download/{file}', [ProductController::class, 'downloadBackup']);
    Route::delete('backup/delete/{file}', [ProductController::class, 'deleteBackup']);
    Route::get('backup/restore/{file}', [ProductController::class, 'restoreBackup']);
    Route::get('backup/restore', [ProductController::class, 'restore'])->name('backup.restore');
    Route::get('backup/restore/confirm/{file}', [ProductController::class, 'confirmRestore']);
    Route::get('backup/restore/execute/{file}', [ProductController::class, 'executeRestore']);
    Route::get('backup/restore/progress', [ProductController::class, 'restoreProgress']);
   Route::get('backup/restore/status', [ProductController::class, 'restoreStatus']);
   Route::get('backup/restore/complete', [ProductController::class, 'restoreComplete']);
   Route::get('backup/restore/error', [ProductController::class, 'restoreError']);
   Route::get('backup/restore/rollback', [ProductController::class, 'rollbackRestore']);
   Route::get('backup/rollback', [ProductController::class, 'rollback']);
   Route::get('backup/rollback/confirm', [ProductController::class, 'confirmRollback']);
   Route::post('auditlogs',[AuditLogController::class,'create']);
   Route::post('auditlogs/store',[AuditLogController::class,'store']);
   Route::get('auditlogs/{id}/edit',[AuditLogController::class,'store']);
   Route::resource('auditlogs', AuditLogController::class);
   Route::get('auditlogs/{id}/edit', [AuditLogController::class, 'edit']);
   Route::put('auditlogs/{id}', [AuditLogController::class, 'update']);
   Route::delete('auditlogs/{id}', [AuditLogController::class, 'destroy']);
   Route::get('auditlogs/{id}/show', [AuditLogController::class, 'show']);
   Route::get('departments', [DepartmentController::class, 'index']);
   Route::post('departments/create',[DepartmentController::class,'create']);
   Route::post('departments/store',[DepartmentController::class,'store']);
   Route::get('departments/{id}/edit', [DepartmentController::class, 'edit']);
   Route::put('departments/{id}', [DepartmentController::class, 'update']);
   Route::delete('departments/{id}', [DepartmentController::class, 'destroy']);
   Route::get('departments/{id}/show', [DepartmentController::class, 'show']);
   Route::get('orders',[OrderController::class,'index']);
   Route::post('orders/create', [OrderController::class, 'create']);
   Route::post('orders/store', [OrderController::class, 'store']);
   Route::get('orders/{id}/edit', [OrderController::class, 'edit']);
   Route::put('orders/{id}', [OrderController::class, 'update']);
   Route::delete('orders/{id}', [OrderController::class, 'destroy']);
   Route::get('orders/{id}/show', [OrderController::class, 'show']);
   Route::get('accounts',[AccountController::class,'index']);
   Route::resource('accounts', AccountController::class);
   Route::get('accounts/{id}/edit', [AccountController::class, 'edit']);
   Route::put('accounts/{id}', [AccountController::class, 'update']);
   Route::delete('accounts/{id}', [AccountController::class, 'destroy']);
   Route::get('accounts/{id}/show', [AccountController::class, 'show']);
    Route::get('users', [AccountController::class, 'index']);
   Route::get('profile', [AccountController::class, 'profile'])->name('profile');
   Route::put('profile/update', [AccountController::class, 'updateProfile']);
   Route::put('profile/password', [AccountController::class, 'updatePassword']);
   Route::get('profile/change-password', [AccountController::class, 'changePassword']);
   Route::get('attendance',[AttendanceController::class, 'index']);
   Route::get('attendance/{id}/edit', [AttendanceController::class, 'edit']);
   Route::put('attendance/{id}', [AttendanceController::class, 'update']);
   Route::post('attendance/create', [AttendanceController::class, 'create']);
   Route::post('attendance/store', [AttendanceController::class, 'store']);
   Route::delete('attendance/{id}', [AttendanceController::class, 'destroy']);
   Route::get('attendance/{id}/show', [AttendanceController::class, 'show']);
   Route::get('attendance/report', [AttendanceController::class, 'report'])->name('attendance.report');
   Route::get('attendance/report/data', [AttendanceController::class, 'reportData']);
   Route::get('attendance/report/export', [AttendanceController::class, 'exportReport']);
   Route::get('customers',[CustomerController::class, 'index' ]);
   Route::post('customers/create', [CustomerController::class, 'create']);
   Route::post('customers/store', [CustomerController::class, 'store']);
   Route::get('customers/{id}/edit', [CustomerController::class, 'edit']);
   Route::put('customers/{id}', [CustomerController::class, 'update']);
   Route::delete('customers/{id}', [CustomerController::class, 'destroy']);
   Route::get('customers/{id}/show', [CustomerController::class, 'show']);
   Route::get('customers/import', [CustomerController::class, 'import'])->name('customers.import');
   Route::post('customers/import', [CustomerController::class, 'doImport']);
   Route::get('employees',[EmployeeController::class,'index']);
   Route::post('employees/create', [EmployeeController::class, 'create']);
   Route::post('employees/store', [EmployeeController::class, 'store']);
   Route::get('employees/{id}/edit', [EmployeeController::class, 'edit']);
   Route::put('employees/{id}', [EmployeeController::class, 'update']);
   Route::delete('employees/{id}', [EmployeeController::class, 'destroy']);
   Route::get('employees/{id}/show', [EmployeeController::class, 'show']);
   Route::get('expenseCategory',[ExpenseCategoryController::class,'index']);
   Route::post('expenseCategory/create', [ExpenseCategoryController::class, 'create']);
   Route::post('expenseCategory/store', [ExpenseCategoryController::class, 'store']);
   Route::get('expenseCategory/{id}/edit', [ExpenseCategoryController::class, 'edit']);
   Route::put('expenseCategory/{id}', [ExpenseCategoryController::class, 'update']);
   Route::delete('expenseCategory/{id}', [ExpenseCategoryController::class, 'destroy']);
   Route::get('invoices',[InvoiceController::class,'index']);
   Route::post('invoices/create', [InvoiceController::class, 'create']);
   Route::post('invoices/store', [InvoiceController::class, 'store']);
   Route::get('invoices/{id}/edit', [InvoiceController::class, 'edit']);
   Route::delete('invoices/{id}', [InvoiceController::class, 'destroy']);
   Route::get('invoices/{id}/show', [InvoiceController::class, 'show']);
   Route::get('notifications',[NotificationController::class, 'index' ]);
   Route::get('notifications/mark-as-read', [NotificationController::class, 'markAsRead']);
   Route::get('notifications/{id}/show', [NotificationController::class, 'show']);
   Route::get('notifications/{id}/edit', [NotificationController::class, 'edit']);
   Route::put('notifications/{id}', [NotificationController::class, 'update']);
   Route::delete('notifications/{id}', [NotificationController::class, 'destroy']);
   Route::get('notifications/create', [NotificationController::class, 'create']);
   Route::post('notifications/store', [NotificationController::class, 'store']);
   Route::get('notifications/read', [NotificationController::class, 'read']);
   Route::get('notifications/unread', [NotificationController::class, 'unread']);
   Route::get('notifications/all', [NotificationController::class, 'all']);
   Route::get('leave_requests',[LeaveRequestController::class, 'index']);
   Route::post('leave_requests/create', [LeaveRequestController::class, 'create']);
   Route::post('leave_requests/store', [LeaveRequestController::class, 'store']);
   Route::get('leave_requests/{id}/edit', [LeaveRequestController::class, 'edit']);
   Route::put('leave_requests/{id}', [LeaveRequestController::class, 'update']);
   Route::delete('leave_requests/{id}', [LeaveRequestController::class, 'destroy']);
   Route::get('leave_requests/{id}/show', [LeaveRequestController::class, 'show']);
   Route::get('payments',[PaymentController::class, 'index' ]);
   Route::post('payments/create', [PaymentController::class, 'create']);
   Route::post('payments/store', [PaymentController::class, 'store']);
   Route::get('payments/{id}/edit', [PaymentController::class, 'edit']);
   Route::put('payments/{id}', [PaymentController::class, 'update']);
   Route::delete('payments/{id}', [PaymentController::class, 'destroy']);
   Route::get('payments/{id}/show', [PaymentController::class, 'show']);
   Route::get('permissions',[PermissionController::class, 'index' ])->name('permissions');
   Route::post('permissions/create', [PermissionController::class, 'create']);
   Route::post('permissions/store', [PermissionController::class, 'store']);
   Route::get('permissions/{id}/edit', [PermissionController::class, 'edit']);
   Route::put('permissions/{id}', [PermissionController::class, 'update']);
   Route::delete('permissions/{id}', [PermissionController::class, 'destroy']);
   Route::get('permissions/{id}/show', [PermissionController::class, 'show']);
   Route::get('roles',[RoleController::class, 'index' ]);
   Route::post('roles/create', [RoleController::class, 'create']);
   Route::post('roles/store', [RoleController::class, 'store']);
   Route::get('roles/{id}/edit', [RoleController::class, 'edit']);
   Route::put('roles/{id}', [RoleController::class, 'update']);
   
});

require __DIR__.'/settings.php';
